### PR TITLE
add setup.py

### PR DESCRIPTION
**Pull request by cmonagle**
Warning: might break existing imports

### CODE REVIEW

**Comment by cmonagle** [comment]
I thought I had flagged this earlier, sorry for letting it get stale!

Does anyone have bandwidth to point me how to fix the tests (or just fix them, which risks to be fater)? This might be a breaking change too. For context, scoping it to a folder seems necessary to package it as a pip dependency. I had played around with a lot of alternative approaches, but none of them seemed to allow imports from another package to resolve correctly.

**Comment by npaun** [comment]
This will break every C++ project and every Python project.

**Comment by npaun** [comment]
Potentially, you could rename `namedstructBindings` to `include/namedstruct`. This way we'd only need to change _CMake_ and not the actual C++ files.  Try to fix the paths in the `CMakeLists.txt` file at the project root - might be enough to get the tests working again.. Ping me next week to discuss if you'd like.

**Comment by gcamp** [comment]
@npaun as a background I told @cmonagle it was ok to break code compatibility if that was the way to fix the build in his context. Your idea sounds good.

**Review by npaun — APPROVED** [review]
Initial install worked for compress and bgtfsLib. Might be some nuisances in handling namedstruct upgrades but I think it's good to merge now.

**Pull request merged**
